### ISSUE TITLE
how to ask questions

### ISSUE THREAD

**Issue by rjesteban** [arnellebalane/ama#1]
unsaon nako pagpangutana kuya? hehehe

**Comment by arnellebalane** [comment]
I don't even know how to answer this so I let Google do it for me hahaha :stuck_out_tongue: 

![image](https://cloud.githubusercontent.com/assets/1428598/14374923/4aab4632-fd8e-11e5-8389-986736b9afe6.png)

But seriously though, you can ask anything you want by opening an issue in this repo. I'll answer them if I can, but also tell you if I can't :smile:
