### ISSUE TITLE
Cmsc 132

### ISSUE THREAD

**Issue by rjesteban** [arnellebalane/ama#5]
I failed in our quiz, and then in our first long exam. It seems the way it is taught that bores me, and now I'm starting to hate the subject. Can you share some pro tips to me how to pass this subject? huhuhuhu T.T
# ComputerArchitecture

**Comment by jedijulia** [comment]
The first step to passing a subject even when you hate it is to completely **isolate your feelings** from your goals. As much as we would all want to learn things in a way that piques our interest, sometimes things just don't go the way we want (that's life) and we have to find a way to get around things ourselves. Find ways to make the subject interesting for you (read more on your own) but if that doesn't work, then turn to the difficult job of just **sucking it up**. Remember what you want in life (or in school, or maybe school is life) and how much you want it! You will soon remember just how much you're willing to do for those goals and how little of a roadblock a boring subject really is. :wink:

**Comment by arnellebalane** [comment]
^ read @jedijulia 's advice haha :100:
