### ISSUE TITLE
Web framework

### ISSUE THREAD

**Issue by rjesteban** [arnellebalane/ama#6]
Aside from bootstrap, foundation, and semantic ui, unsa man mas nice nga frontend framework kuya? kana sigurong di kaayo dagko (like 14) ang font size...

**Comment by arnellebalane** [comment]
Between the three frameworks that you mentioned, I personally prefer using Semantic UI over the rest even though I don't really use them that much.

> kana sigurong di kaayo dagko (like 14) ang font size...

I believe those frameworks have some way of configuring their defaults (including the font size), so you might want to read their documentations to find out how to do so haha.

**Comment by arnellebalane** [comment]
I just stumbled upon another frontend framework today, [Materialize](http://materializecss.com/). It's based on Google's Material Design.
