### ISSUE TITLE
Automata Theory and Languages

### ISSUE THREAD

**Issue by rjesteban** [arnellebalane/ama#7]
Aside from NFA->DFA converter and Regex parser, what are other possible projects can I do (that is automata ang language theory related)?

**Comment by arnellebalane** [comment]
Here are a few project ideas that I can think of right now (I also want to work on some of these stuff so maybe we can collaborate haha)
- visual NFA/DFA constructor (like [this one](https://github.com/arnellebalane/automata))
- regex parser to parse javascript's regex
- make a parser for a language that you want, and then construct an abstract syntax tree from it
