### ISSUE TITLE
ethics and right

### ISSUE THREAD

**Issue by rjesteban** [arnellebalane/ama#8]
Were having trouble with a course lately. There are some issues with our 'sensei'. Most of my classmates can't tolerate the sensei anymore. Almost all are willing to write a complaint. I just wanna ask if this kind of thing helps? or just makes our situation worse? :/ or is it better to stay silent? and have that cycle to be experienced by the next batches?

**Comment by arnellebalane** [comment]
I think you should. Maybe it wouldn't change anything for your batch, but it most probably will for the next batches. Maybe you are experiencing that situation because the batches before you chose to stay silent.
